package com.in.fsa.AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 08 15:02:47 IST 2017
// ---------------------------------------------------------------------
public interface AM extends ApplicationModule {
  String saveorUpdate();
}
