package com.in.fsa.VO;

import com.in.fsa.EO.FacilityTxnEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 14 22:39:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FacilityTxnVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum {
    TxnId {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getTxnId();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setTxnId((Number)value);
      }
    }
    ,
    DocumentNumber {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getDocumentNumber();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setDocumentNumber((Number)value);
      }
    }
    ,
    FacilityNumber {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getFacilityNumber();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setFacilityNumber((String)value);
      }
    }
    ,
    TotalAmount {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getTotalAmount();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setTotalAmount((Number)value);
      }
    }
    ,
    Description {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getDescription();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setDescription((String)value);
      }
    }
    ,
    FacilityDate {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getFacilityDate();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setFacilityDate((Date)value);
      }
    }
    ,
    ExpiryDate {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getExpiryDate();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setExpiryDate((Date)value);
      }
    }
    ,
    ExtendedExpiryDate {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getExtendedExpiryDate();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setExtendedExpiryDate((Date)value);
      }
    }
    ,
    NumberOfExtends {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getNumberOfExtends();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setNumberOfExtends((Number)value);
      }
    }
    ,
    LegalEntity {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getLegalEntity();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setLegalEntity((String)value);
      }
    }
    ,
    BusinessUnit {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getBusinessUnit();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setBusinessUnit((String)value);
      }
    }
    ,
    BankName {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getBankName();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setBankName((String)value);
      }
    }
    ,
    BranchName {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getBranchName();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setBranchName((String)value);
      }
    }
    ,
    AccountName {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getAccountName();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setAccountName((String)value);
      }
    }
    ,
    CurrencyCode {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getCurrencyCode();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setCurrencyCode((String)value);
      }
    }
    ,
    BankAccountNumber {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getBankAccountNumber();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setBankAccountNumber((String)value);
      }
    }
    ,
    ProjectName {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getProjectName();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setProjectName((String)value);
      }
    }
    ,
    ProjectNumber {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getProjectNumber();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setProjectNumber((String)value);
      }
    }
    ,
    Area {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getArea();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setArea((String)value);
      }
    }
    ,
    CreatedBy {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getCreatedBy();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setCreatedBy((String)value);
      }
    }
    ,
    CreationDate {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getCreationDate();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setCreationDate((Date)value);
      }
    }
    ,
    LastUpdatedBy {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getLastUpdatedBy();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setLastUpdatedBy((String)value);
      }
    }
    ,
    LastUpdatedDate {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getLastUpdatedDate();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setLastUpdatedDate((Date)value);
      }
    }
    ,
    FacilitySynBankVO {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getFacilitySynBankVO();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    FacilityFinancialVO {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getFacilityFinancialVO();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    FacilityExtnVO {
      public Object get(FacilityTxnVORowImpl obj) {
        return obj.getFacilityExtnVO();
      }

      public void put(FacilityTxnVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(FacilityTxnVORowImpl object);

    public abstract void put(FacilityTxnVORowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int TXNID = AttributesEnum.TxnId.index();
  public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
  public static final int FACILITYNUMBER = AttributesEnum.FacilityNumber.index();
  public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
  public static final int DESCRIPTION = AttributesEnum.Description.index();
  public static final int FACILITYDATE = AttributesEnum.FacilityDate.index();
  public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
  public static final int EXTENDEDEXPIRYDATE = AttributesEnum.ExtendedExpiryDate.index();
  public static final int NUMBEROFEXTENDS = AttributesEnum.NumberOfExtends.index();
  public static final int LEGALENTITY = AttributesEnum.LegalEntity.index();
  public static final int BUSINESSUNIT = AttributesEnum.BusinessUnit.index();
  public static final int BANKNAME = AttributesEnum.BankName.index();
  public static final int BRANCHNAME = AttributesEnum.BranchName.index();
  public static final int ACCOUNTNAME = AttributesEnum.AccountName.index();
  public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
  public static final int BANKACCOUNTNUMBER = AttributesEnum.BankAccountNumber.index();
  public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
  public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
  public static final int AREA = AttributesEnum.Area.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
  public static final int FACILITYSYNBANKVO = AttributesEnum.FacilitySynBankVO.index();
  public static final int FACILITYFINANCIALVO = AttributesEnum.FacilityFinancialVO.index();
  public static final int FACILITYEXTNVO = AttributesEnum.FacilityExtnVO.index();

  /**
   * This is the default constructor (do not remove).
   */
  public FacilityTxnVORowImpl() {
  }

  /**
   * Gets FacilityTxnEO entity object.
   * @return the FacilityTxnEO
   */
  public FacilityTxnEOImpl getFacilityTxnEO() {
    return (FacilityTxnEOImpl)getEntity(0);
  }

  /**
   * Gets the attribute value for TXN_ID using the alias name TxnId.
   * @return the TXN_ID
   */
  public Number getTxnId() {
    return (Number) getAttributeInternal(TXNID);
  }

  /**
   * Sets <code>value</code> as attribute value for TXN_ID using the alias name TxnId.
   * @param value value to set the TXN_ID
   */
  public void setTxnId(Number value) {
    setAttributeInternal(TXNID, value);
  }

  /**
   * Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
   * @return the DOCUMENT_NUMBER
   */
  public Number getDocumentNumber() {
    return (Number) getAttributeInternal(DOCUMENTNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
   * @param value value to set the DOCUMENT_NUMBER
   */
  public void setDocumentNumber(Number value) {
    setAttributeInternal(DOCUMENTNUMBER, value);
  }

  /**
   * Gets the attribute value for FACILITY_NUMBER using the alias name FacilityNumber.
   * @return the FACILITY_NUMBER
   */
  public String getFacilityNumber() {
    return (String) getAttributeInternal(FACILITYNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for FACILITY_NUMBER using the alias name FacilityNumber.
   * @param value value to set the FACILITY_NUMBER
   */
  public void setFacilityNumber(String value) {
    setAttributeInternal(FACILITYNUMBER, value);
  }

  /**
   * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
   * @return the TOTAL_AMOUNT
   */
  public Number getTotalAmount() {
    return (Number) getAttributeInternal(TOTALAMOUNT);
  }

  /**
   * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
   * @param value value to set the TOTAL_AMOUNT
   */
  public void setTotalAmount(Number value) {
    setAttributeInternal(TOTALAMOUNT, value);
  }

  /**
   * Gets the attribute value for DESCRIPTION using the alias name Description.
   * @return the DESCRIPTION
   */
  public String getDescription() {
    return (String) getAttributeInternal(DESCRIPTION);
  }

  /**
   * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
   * @param value value to set the DESCRIPTION
   */
  public void setDescription(String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * Gets the attribute value for FACILITY_DATE using the alias name FacilityDate.
   * @return the FACILITY_DATE
   */
  public Date getFacilityDate() {
    return (Date) getAttributeInternal(FACILITYDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for FACILITY_DATE using the alias name FacilityDate.
   * @param value value to set the FACILITY_DATE
   */
  public void setFacilityDate(Date value) {
    setAttributeInternal(FACILITYDATE, value);
  }

  /**
   * Gets the attribute value for EXPIRY_DATE using the alias name ExpiryDate.
   * @return the EXPIRY_DATE
   */
  public Date getExpiryDate() {
    return (Date) getAttributeInternal(EXPIRYDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for EXPIRY_DATE using the alias name ExpiryDate.
   * @param value value to set the EXPIRY_DATE
   */
  public void setExpiryDate(Date value) {
    setAttributeInternal(EXPIRYDATE, value);
  }

  /**
   * Gets the attribute value for EXTENDED_EXPIRY_DATE using the alias name ExtendedExpiryDate.
   * @return the EXTENDED_EXPIRY_DATE
   */
  public Date getExtendedExpiryDate() {
    return (Date) getAttributeInternal(EXTENDEDEXPIRYDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for EXTENDED_EXPIRY_DATE using the alias name ExtendedExpiryDate.
   * @param value value to set the EXTENDED_EXPIRY_DATE
   */
  public void setExtendedExpiryDate(Date value) {
    setAttributeInternal(EXTENDEDEXPIRYDATE, value);
  }

  /**
   * Gets the attribute value for NUMBER_OF_EXTENDS using the alias name NumberOfExtends.
   * @return the NUMBER_OF_EXTENDS
   */
  public Number getNumberOfExtends() {
    return (Number) getAttributeInternal(NUMBEROFEXTENDS);
  }

  /**
   * Sets <code>value</code> as attribute value for NUMBER_OF_EXTENDS using the alias name NumberOfExtends.
   * @param value value to set the NUMBER_OF_EXTENDS
   */
  public void setNumberOfExtends(Number value) {
    setAttributeInternal(NUMBEROFEXTENDS, value);
  }

  /**
   * Gets the attribute value for LEGAL_ENTITY using the alias name LegalEntity.
   * @return the LEGAL_ENTITY
   */
  public String getLegalEntity() {
    return (String) getAttributeInternal(LEGALENTITY);
  }

  /**
   * Sets <code>value</code> as attribute value for LEGAL_ENTITY using the alias name LegalEntity.
   * @param value value to set the LEGAL_ENTITY
   */
  public void setLegalEntity(String value) {
    setAttributeInternal(LEGALENTITY, value);
  }

  /**
   * Gets the attribute value for BUSINESS_UNIT using the alias name BusinessUnit.
   * @return the BUSINESS_UNIT
   */
  public String getBusinessUnit() {
    return (String) getAttributeInternal(BUSINESSUNIT);
  }

  /**
   * Sets <code>value</code> as attribute value for BUSINESS_UNIT using the alias name BusinessUnit.
   * @param value value to set the BUSINESS_UNIT
   */
  public void setBusinessUnit(String value) {
    setAttributeInternal(BUSINESSUNIT, value);
  }

  /**
   * Gets the attribute value for BANK_NAME using the alias name BankName.
   * @return the BANK_NAME
   */
  public String getBankName() {
    return (String) getAttributeInternal(BANKNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for BANK_NAME using the alias name BankName.
   * @param value value to set the BANK_NAME
   */
  public void setBankName(String value) {
    setAttributeInternal(BANKNAME, value);
  }

  /**
   * Gets the attribute value for BRANCH_NAME using the alias name BranchName.
   * @return the BRANCH_NAME
   */
  public String getBranchName() {
    return (String) getAttributeInternal(BRANCHNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for BRANCH_NAME using the alias name BranchName.
   * @param value value to set the BRANCH_NAME
   */
  public void setBranchName(String value) {
    setAttributeInternal(BRANCHNAME, value);
  }

  /**
   * Gets the attribute value for ACCOUNT_NAME using the alias name AccountName.
   * @return the ACCOUNT_NAME
   */
  public String getAccountName() {
    return (String) getAttributeInternal(ACCOUNTNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for ACCOUNT_NAME using the alias name AccountName.
   * @param value value to set the ACCOUNT_NAME
   */
  public void setAccountName(String value) {
    setAttributeInternal(ACCOUNTNAME, value);
  }

  /**
   * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
   * @return the CURRENCY_CODE
   */
  public String getCurrencyCode() {
    return (String) getAttributeInternal(CURRENCYCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
   * @param value value to set the CURRENCY_CODE
   */
  public void setCurrencyCode(String value) {
    setAttributeInternal(CURRENCYCODE, value);
  }

  /**
   * Gets the attribute value for BANK_ACCOUNT_NUMBER using the alias name BankAccountNumber.
   * @return the BANK_ACCOUNT_NUMBER
   */
  public String getBankAccountNumber() {
    return (String) getAttributeInternal(BANKACCOUNTNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for BANK_ACCOUNT_NUMBER using the alias name BankAccountNumber.
   * @param value value to set the BANK_ACCOUNT_NUMBER
   */
  public void setBankAccountNumber(String value) {
    setAttributeInternal(BANKACCOUNTNUMBER, value);
  }

  /**
   * Gets the attribute value for PROJECT_NAME using the alias name ProjectName.
   * @return the PROJECT_NAME
   */
  public String getProjectName() {
    return (String) getAttributeInternal(PROJECTNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for PROJECT_NAME using the alias name ProjectName.
   * @param value value to set the PROJECT_NAME
   */
  public void setProjectName(String value) {
    setAttributeInternal(PROJECTNAME, value);
  }

  /**
   * Gets the attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
   * @return the PROJECT_NUMBER
   */
  public String getProjectNumber() {
    return (String) getAttributeInternal(PROJECTNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for PROJECT_NUMBER using the alias name ProjectNumber.
   * @param value value to set the PROJECT_NUMBER
   */
  public void setProjectNumber(String value) {
    setAttributeInternal(PROJECTNUMBER, value);
  }

  /**
   * Gets the attribute value for AREA using the alias name Area.
   * @return the AREA
   */
  public String getArea() {
    return (String) getAttributeInternal(AREA);
  }

  /**
   * Sets <code>value</code> as attribute value for AREA using the alias name Area.
   * @param value value to set the AREA
   */
  public void setArea(String value) {
    setAttributeInternal(AREA, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public String getCreatedBy() {
    return (String) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Date getCreationDate() {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @return the LAST_UPDATED_BY
   */
  public String getLastUpdatedBy() {
    return (String) getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @param value value to set the LAST_UPDATED_BY
   */
  public void setLastUpdatedBy(String value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
   * @return the LAST_UPDATED_DATE
   */
  public Date getLastUpdatedDate() {
    return (Date) getAttributeInternal(LASTUPDATEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
   * @param value value to set the LAST_UPDATED_DATE
   */
  public void setLastUpdatedDate(Date value) {
    setAttributeInternal(LASTUPDATEDDATE, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link FacilitySynBankVO.
   */
  public RowIterator getFacilitySynBankVO() {
    return (RowIterator)getAttributeInternal(FACILITYSYNBANKVO);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link FacilityFinancialVO.
   */
  public RowIterator getFacilityFinancialVO() {
    return (RowIterator)getAttributeInternal(FACILITYFINANCIALVO);
  }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FacilityExtnVO.
     */
    public RowIterator getFacilityExtnVO() {
        return (RowIterator)getAttributeInternal(FACILITYEXTNVO);
    }


  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
