package com.in.fsa.VO;

import com.in.fsa.EO.FacilityFinancialEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 14 22:46:03 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FacilityFinancialVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum {
    Id {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getId();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setId((Number)value);
      }
    }
    ,
    TxnId {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getTxnId();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setTxnId((Number)value);
      }
    }
    ,
    AmountOrg {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getAmountOrg();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setAmountOrg((Number)value);
      }
    }
    ,
    AmountExtd {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getAmountExtd();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setAmountExtd((Number)value);
      }
    }
    ,
    CreatedBy {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getCreatedBy();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setCreatedBy((String)value);
      }
    }
    ,
    CreationDate {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getCreationDate();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setCreationDate((Date)value);
      }
    }
    ,
    LastUpdatedBy {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getLastUpdatedBy();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setLastUpdatedBy((String)value);
      }
    }
    ,
    LastUpdatedDate {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getLastUpdatedDate();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setLastUpdatedDate((Date)value);
      }
    }
    ,
    FacilityType {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getFacilityType();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setFacilityType((String)value);
      }
    }
    ,
    FacilityLovVo1 {
      public Object get(FacilityFinancialVORowImpl obj) {
        return obj.getFacilityLovVo1();
      }

      public void put(FacilityFinancialVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(FacilityFinancialVORowImpl object);

    public abstract void put(FacilityFinancialVORowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int ID = AttributesEnum.Id.index();
  public static final int TXNID = AttributesEnum.TxnId.index();
  public static final int AMOUNTORG = AttributesEnum.AmountOrg.index();
  public static final int AMOUNTEXTD = AttributesEnum.AmountExtd.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
  public static final int FACILITYTYPE = AttributesEnum.FacilityType.index();
  public static final int FACILITYLOVVO1 = AttributesEnum.FacilityLovVo1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public FacilityFinancialVORowImpl() {
  }

  /**
   * Gets FacilityFinancialEO entity object.
   * @return the FacilityFinancialEO
   */
  public FacilityFinancialEOImpl getFacilityFinancialEO() {
    return (FacilityFinancialEOImpl)getEntity(0);
  }

  /**
   * Gets the attribute value for ID using the alias name Id.
   * @return the ID
   */
  public Number getId() {
    return (Number) getAttributeInternal(ID);
  }

  /**
   * Sets <code>value</code> as attribute value for ID using the alias name Id.
   * @param value value to set the ID
   */
  public void setId(Number value) {
    setAttributeInternal(ID, value);
  }

  /**
   * Gets the attribute value for TXN_ID using the alias name TxnId.
   * @return the TXN_ID
   */
  public Number getTxnId() {
    return (Number) getAttributeInternal(TXNID);
  }

  /**
   * Sets <code>value</code> as attribute value for TXN_ID using the alias name TxnId.
   * @param value value to set the TXN_ID
   */
  public void setTxnId(Number value) {
    setAttributeInternal(TXNID, value);
  }

  /**
   * Gets the attribute value for AMOUNT_ORG using the alias name AmountOrg.
   * @return the AMOUNT_ORG
   */
  public Number getAmountOrg() {
    return (Number) getAttributeInternal(AMOUNTORG);
  }

  /**
   * Sets <code>value</code> as attribute value for AMOUNT_ORG using the alias name AmountOrg.
   * @param value value to set the AMOUNT_ORG
   */
  public void setAmountOrg(Number value) {
    setAttributeInternal(AMOUNTORG, value);
  }

  /**
   * Gets the attribute value for AMOUNT_EXTD using the alias name AmountExtd.
   * @return the AMOUNT_EXTD
   */
  public Number getAmountExtd() {
    return (Number) getAttributeInternal(AMOUNTEXTD);
  }

  /**
   * Sets <code>value</code> as attribute value for AMOUNT_EXTD using the alias name AmountExtd.
   * @param value value to set the AMOUNT_EXTD
   */
  public void setAmountExtd(Number value) {
    setAttributeInternal(AMOUNTEXTD, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public String getCreatedBy() {
    return (String) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Date getCreationDate() {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @return the LAST_UPDATED_BY
   */
  public String getLastUpdatedBy() {
    return (String) getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
   * @param value value to set the LAST_UPDATED_BY
   */
  public void setLastUpdatedBy(String value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
   * @return the LAST_UPDATED_DATE
   */
  public Date getLastUpdatedDate() {
    return (Date) getAttributeInternal(LASTUPDATEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
   * @param value value to set the LAST_UPDATED_DATE
   */
  public void setLastUpdatedDate(Date value) {
    setAttributeInternal(LASTUPDATEDDATE, value);
  }

  /**
   * Gets the attribute value for FACILITY_TYPE using the alias name FacilityType.
   * @return the FACILITY_TYPE
   */
  public String getFacilityType() {
    return (String) getAttributeInternal(FACILITYTYPE);
  }

  /**
   * Sets <code>value</code> as attribute value for FACILITY_TYPE using the alias name FacilityType.
   * @param value value to set the FACILITY_TYPE
   */
  public void setFacilityType(String value) {
    setAttributeInternal(FACILITYTYPE, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> FacilityLovVo1.
   */
  public RowSet getFacilityLovVo1() {
    return (RowSet)getAttributeInternal(FACILITYLOVVO1);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
