package com.in.fsa.AppModule.client;

import com.in.fsa.AppModule.common.AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 08 15:02:48 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AMClient extends ApplicationModuleImpl implements AM {
  /**
   * This is the default constructor (do not remove).
   */
  public AMClient() {
  }

  public String saveorUpdate() {
    Object _ret = this.riInvokeExportedMethod(this,"saveorUpdate",null,null);
    return (String)_ret;
  }
}
