package com.in.fsa.AppModule;

import com.in.fsa.AppModule.common.AM;

import com.in.fsa.EO.FacilityTxnEOImpl;

import com.in.fsa.VO.FacilityAmtSumDetVORowImpl;
import com.in.fsa.VO.FacilityAmtSumVORowImpl;
import com.in.fsa.VO.FacilityExtnVORowImpl;
import com.in.fsa.VO.FacilityFinancialVORowImpl;
import com.in.fsa.VO.FacilitySynBankVORowImpl;
import com.in.fsa.VO.FacilityTxnVORowImpl;

import java.util.Date;

import oracle.adf.share.ADFContext;

import oracle.adf.share.security.SecurityContext;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Char;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 08 12:38:33 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AMImpl extends ApplicationModuleImpl implements AM {
    /**
     * This is the default constructor (do not remove).
     */
    public AMImpl() {
    }

    /**
     * Container's getter for FacilityAmtSumDetVO1.
     * @return FacilityAmtSumDetVO1
     */
    public ViewObjectImpl getFacilityAmtSumDetVO1() {
        return (ViewObjectImpl)findViewObject("FacilityAmtSumDetVO1");
    }

    /**
     * Container's getter for FacilityAmtSumVO1.
     * @return FacilityAmtSumVO1
     */
    public ViewObjectImpl getFacilityAmtSumVO1() {
        return (ViewObjectImpl)findViewObject("FacilityAmtSumVO1");
    }

    /**
     * Container's getter for FacilityFinancialVO1.
     * @return FacilityFinancialVO1
     */
    public ViewObjectImpl getFacilityFinancialVO1() {
        return (ViewObjectImpl)findViewObject("FacilityFinancialVO1");
    }

    /**
     * Container's getter for FacilityHdrVO1.
     * @return FacilityHdrVO1
     */
    public ViewObjectImpl getFacilityHdrVO1() {
        return (ViewObjectImpl)findViewObject("FacilityHdrVO1");
    }

    /**
     * Container's getter for FacilitySynBankVO1.
     * @return FacilitySynBankVO1
     */
    public ViewObjectImpl getFacilitySynBankVO1() {
        return (ViewObjectImpl)findViewObject("FacilitySynBankVO1");
    }

    /**
     * Container's getter for FacilityTxnVO1.
     * @return FacilityTxnVO1
     */
    public ViewObjectImpl getFacilityTxnVO1() {
        return (ViewObjectImpl)findViewObject("FacilityTxnVO1");
    }

    /**
     * Container's getter for FacilitySynBankVO2.
     * @return FacilitySynBankVO2
     */
    public ViewObjectImpl getFacilitySynBankVO2() {
        return (ViewObjectImpl)findViewObject("FacilitySynBankVO2");
    }

    /**
     * Container's getter for FacilityTxnVO2.
     * @return FacilityTxnVO2
     */
    public ViewObjectImpl getFacilityTxnVO2() {
        return (ViewObjectImpl)findViewObject("FacilityTxnVO2");
    }

    /**
     * Container's getter for FacilityFinancialVO2.
     * @return FacilityFinancialVO2
     */
    public ViewObjectImpl getFacilityFinancialVO2() {
        return (ViewObjectImpl)findViewObject("FacilityFinancialVO2");
    }

    /**
     * Container's getter for FacilityAmtSumDetVO2.
     * @return FacilityAmtSumDetVO2
     */
    public ViewObjectImpl getFacilityAmtSumDetVO2() {
        return (ViewObjectImpl)findViewObject("FacilityAmtSumDetVO2");
    }

    /**
     * Container's getter for SysC008514Link1.
     * @return SysC008514Link1
     */
    public ViewLinkImpl getSysC008514Link1() {
        return (ViewLinkImpl)findViewLink("SysC008514Link1");
    }

    /**
     * Container's getter for SysC008512Link1.
     * @return SysC008512Link1
     */
    public ViewLinkImpl getSysC008512Link1() {
        return (ViewLinkImpl)findViewLink("SysC008512Link1");
    }

    /**
     * Container's getter for SysC008516Link1.
     * @return SysC008516Link1
     */
    public ViewLinkImpl getSysC008516Link1() {
        return (ViewLinkImpl)findViewLink("SysC008516Link1");
    }

    /**
     * Container's getter for SysC008520Link1.
     * @return SysC008520Link1
     */
    public ViewLinkImpl getSysC008520Link1() {
        return (ViewLinkImpl)findViewLink("SysC008520Link1");
    }

    /**
     * Save Bank Facility
     */
    public String saveorUpdate() {
        ADFContext adfCtx = ADFContext.getCurrent();
        SecurityContext secCntx = adfCtx.getSecurityContext();

        String _user = secCntx.getUserName();
        ViewObject facilityHdrVO = this.getFacilityHdrVO1();
        //       Row hdrCurrentRow=facilityHdrVO.getCurrentRow();
        //      String isCompleteFlag="";
        //       if(hdrCurrentRow != null && hdrCurrentRow.getAttribute("IsComplete") != null)
        //       {
        //        isCompleteFlag = (String)hdrCurrentRow.getAttribute("IsComplete");
        //         System.out.println("IS COMPLETE VAL-->>"+hdrCurrentRow.getAttribute("IsComplete"));
        //       }

        ViewObject facilityTxnVO = this.getFacilityTxnVO1();
        Row txnRow = facilityTxnVO.getCurrentRow();
        facilityHdrVO.setNamedWhereClauseParam("facilityNumber",
                                               txnRow.getAttribute("FacilityNumber"));
        facilityHdrVO.executeQuery();
        Row[] hdrRows = facilityHdrVO.getAllRowsInRange();
        Row hdrRow = null;
        if (hdrRows.length > 0) {
            hdrRow = hdrRows[0];
        }

        System.out.println("TXN ROWS" + facilityTxnVO.getEstimatedRowCount());
        ViewObject facilityFinancialVo = this.getFacilityFinancialVO2();
        Row[] financialRows = facilityFinancialVo.getAllRowsInRange();
        ViewObject facilitySyndictnVo = this.getFacilitySynBankVO2();
        //        Row[] facilitySyndictnRows = facilitySyndictnVo.getAllRowsInRange();
        ViewObject facilityAmtSummVo = this.getFacilityAmtSumVO1();
        Row[] facilityAmtSummRows = facilityAmtSummVo.getAllRowsInRange();
        ViewObject facilityAmtSummDetVo = this.getFacilityAmtSumDetVO2();
        facilityAmtSummDetVo.reset();
        Row[] facilityAmtSummDetRows =
            facilityAmtSummDetVo.getAllRowsInRange();
        System.out.println("Estimated ROw COunt-->>" +
                           facilityAmtSummDetVo.getEstimatedRowCount());
        ViewObject facilityExtnVo = this.getFacilityExtnVO2();
        Row[] facilityExtnRows = facilityExtnVo.getAllRowsInRange();
        String isNewRcrd = "";
        String facNum = "";
        Number docNum = null;
        if (null != hdrRow) {
            isNewRcrd = (String)hdrRow.getAttribute("IsNew");
        }

        if (isNewRcrd != null && !"".equals(isNewRcrd) &&
            "N".equals(isNewRcrd)) {
            hdrRow.setAttribute("FacilityNumber",
                                txnRow.getAttribute("FacilityNumber"));
            hdrRow.setAttribute("IsNew", "N");
            docNum = (Number)hdrRow.getAttribute("DocumentNumber");
            hdrRow.setAttribute("FacilityNumber",
                                txnRow.getAttribute("FacilityNumber"));
            hdrRow.setAttribute("Description",
                                txnRow.getAttribute("Description"));
            hdrRow.setAttribute("TotalAmount",
                                txnRow.getAttribute("TotalAmount"));
            hdrRow.setAttribute("FacilityDate",
                                txnRow.getAttribute("FacilityDate"));
            hdrRow.setAttribute("ExpiryDate",
                                txnRow.getAttribute("ExpiryDate"));
            hdrRow.setAttribute("ExtendedExpiryDate",
                                txnRow.getAttribute("ExtendedExpiryDate"));
            hdrRow.setAttribute("LegalEntity",
                                txnRow.getAttribute("LegalEntity"));
            hdrRow.setAttribute("BusinessUnit",
                                txnRow.getAttribute("BusinessUnit"));
            hdrRow.setAttribute("NumberOfExtends", "");
            //hdrRow.setAttribute("CreatedBy", _user);
            hdrRow.setAttribute("LastUpdatedBy", _user);
            //hdrRow.setAttribute("CreationDate", new Date());
            hdrRow.setAttribute("LastUpdatedDate", new Date());


        } else {
            Number facilityHdrSeq =
                getSequenceVal("XXX_FSA_FIN_FACILITY_HDR_SEQ");
            docNum = facilityHdrSeq;
            Row newHdrRow = facilityHdrVO.createRow();
            newHdrRow.setAttribute("DocumentNumber", facilityHdrSeq);
            newHdrRow.setAttribute("FacilityNumber",
                                   txnRow.getAttribute("FacilityNumber"));
            newHdrRow.setAttribute("Description",
                                   txnRow.getAttribute("Description"));
            newHdrRow.setAttribute("IsNew", "N");
            newHdrRow.setAttribute("TotalAmount",
                                   txnRow.getAttribute("TotalAmount"));
            newHdrRow.setAttribute("FacilityDate",
                                   txnRow.getAttribute("FacilityDate"));
            newHdrRow.setAttribute("ExpiryDate",
                                   txnRow.getAttribute("ExpiryDate"));
            newHdrRow.setAttribute("ExtendedExpiryDate",
                                   txnRow.getAttribute("ExtendedExpiryDate"));
            newHdrRow.setAttribute("LegalEntity",
                                   txnRow.getAttribute("LegalEntity"));
            newHdrRow.setAttribute("BusinessUnit",
                                   txnRow.getAttribute("BusinessUnit"));
            newHdrRow.setAttribute("NumberOfExtends",
                                   txnRow.getAttribute("NumberOfExtends"));
            newHdrRow.setAttribute("IsComplete", "Y");
            newHdrRow.setAttribute("CreatedBy", _user);
            //newHdrRow.setAttribute("LastUpdatedBy", _user);
            newHdrRow.setAttribute("CreationDate", new Date());
            //newHdrRow.setAttribute("LastUpdatedDate", new Date());
            facilityHdrVO.insertRow(newHdrRow);
        }
        facNum = (String)txnRow.getAttribute("FacilityNumber");
        Number facilityTxnSeq = getSequenceVal("XXX_FSA_FIN_FACILITY_TXN_SEQ");
        Row newTxnRow = facilityTxnVO.createRow();
        newTxnRow.setAttribute("TxnId", facilityTxnSeq);
        newTxnRow.setAttribute("FacilityNumber",
                               txnRow.getAttribute("FacilityNumber"));
        newTxnRow.setAttribute("Description",
                               txnRow.getAttribute("Description"));
        newTxnRow.setAttribute("DocumentNumber", docNum);
        newTxnRow.setAttribute("FacilityDate",
                               txnRow.getAttribute("FacilityDate"));
        newTxnRow.setAttribute("TotalAmount",
                               txnRow.getAttribute("TotalAmount"));
        newTxnRow.setAttribute("ExpiryDate",
                               txnRow.getAttribute("ExpiryDate"));
        newTxnRow.setAttribute("ExtendedExpiryDate",
                               txnRow.getAttribute("ExtendedExpiryDate"));
        newTxnRow.setAttribute("LegalEntity",
                               txnRow.getAttribute("LegalEntity"));
        newTxnRow.setAttribute("BusinessUnit",
                               txnRow.getAttribute("BusinessUnit"));
        newTxnRow.setAttribute("BankName", txnRow.getAttribute("BankName"));
        newTxnRow.setAttribute("BranchName",
                               txnRow.getAttribute("BranchName"));
        newTxnRow.setAttribute("AccountName",
                               txnRow.getAttribute("AccountName"));
        newTxnRow.setAttribute("CurrencyCode",
                               txnRow.getAttribute("CurrencyCode"));
        newTxnRow.setAttribute("BankAccountNumber",
                               txnRow.getAttribute("BankAccountNumber"));
        newTxnRow.setAttribute("ProjectName",
                               txnRow.getAttribute("ProjectName"));
        newTxnRow.setAttribute("ProjectNumber",
                               txnRow.getAttribute("ProjectNumber"));
        newTxnRow.setAttribute("Area", txnRow.getAttribute("Area"));
        newTxnRow.setAttribute("NumberOfExtends",
                               txnRow.getAttribute("NumberOfExtends"));
        ;
        newTxnRow.setAttribute("CreatedBy", _user);
        //newTxnRow.setAttribute("LastUpdatedBy", _user);
        newTxnRow.setAttribute("CreationDate", new Date());
        //newTxnRow.setAttribute("LastUpdatedDate", new Date());

        RowSet facilitySyndictnRows =
            (RowSet)txnRow.getAttribute("FacilitySynBankVO");
        while (facilitySyndictnRows.hasNext()) {
            Row facilitySyndictnRow = facilitySyndictnRows.next();
            Number facilitySyndctnSeq =
                getSequenceVal("XXX_FSA_FIN_FACILITY_SYN_SEQ");
            Row newSyndctnRow = facilitySyndictnVo.createRow();
            newSyndctnRow.setAttribute("Id", facilitySyndctnSeq);
            newSyndctnRow.setAttribute("TxnId", facilityTxnSeq);
            newSyndctnRow.setAttribute("Amount",
                                       facilitySyndictnRow.getAttribute("Amount"));
            newSyndctnRow.setAttribute("FacilityType",
                                       facilitySyndictnRow.getAttribute("FacilityType"));
            newSyndctnRow.setAttribute("BankName",
                                       facilitySyndictnRow.getAttribute("BankName"));
            newSyndctnRow.setAttribute("Percentage",
                                       facilitySyndictnRow.getAttribute("Percentage"));
            newSyndctnRow.setAttribute("CreatedBy", _user);
            //newSyndctnRow.setAttribute("LastUpdatedBy", _user);
            newSyndctnRow.setAttribute("CreationDate", new Date());
            //newSyndctnRow.setAttribute("LastUpdatedDate", new Date());
            FacilitySynBankVORowImpl syndctnRowImpl =
                (FacilitySynBankVORowImpl)facilitySyndictnRow;
            if (syndctnRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_MODIFIED ||
                syndctnRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_NEW) {
                facilitySyndictnRow.refresh(Row.REFRESH_UNDO_CHANGES |
                                            Row.REFRESH_WITH_DB_FORGET_CHANGES |
                                            Row.REFRESH_FORGET_NEW_ROWS);
            }
            facilitySyndictnVo.insertRow(newSyndctnRow);
        }

        FacilityTxnVORowImpl txnVOImpl = (FacilityTxnVORowImpl)txnRow;
        if (txnVOImpl.getEntity(0).getEntityState() ==
            Entity.STATUS_MODIFIED ||
            txnVOImpl.getEntity(0).getEntityState() == Entity.STATUS_NEW) {
            txnRow.refresh(Row.REFRESH_UNDO_CHANGES |
                           Row.REFRESH_WITH_DB_FORGET_CHANGES |
                           Row.REFRESH_FORGET_NEW_ROWS);
        }
        facilityTxnVO.insertRow(newTxnRow);

        for (Row financialRow : financialRows) {
            Number facilityFinancialSeq =
                getSequenceVal("XXX_FSA_FIN_FAC_FINANCIAL_SEQ");
            Row newFinancialRow = facilityFinancialVo.createRow();
            newFinancialRow.setAttribute("Id", facilityFinancialSeq);
            newFinancialRow.setAttribute("TxnId", facilityTxnSeq);
            newFinancialRow.setAttribute("FacilityType",
                                         financialRow.getAttribute("FacilityType"));
            newFinancialRow.setAttribute("AmountOrg",
                                         financialRow.getAttribute("AmountOrg"));
            newFinancialRow.setAttribute("AmountExtd",
                                         financialRow.getAttribute("AmountExtd"));
            newFinancialRow.setAttribute("CreatedBy", _user);
            //newFinancialRow.setAttribute("LastUpdatedBy", _user);
            newFinancialRow.setAttribute("CreationDate", new Date());
            //newFinancialRow.setAttribute("LastUpdatedDate", new Date());


            FacilityFinancialVORowImpl financialRowImpl =
                (FacilityFinancialVORowImpl)financialRow;
            if (financialRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_MODIFIED ||
                financialRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_NEW) {
                financialRow.refresh(Row.REFRESH_UNDO_CHANGES |
                                     Row.REFRESH_WITH_DB_FORGET_CHANGES |
                                     Row.REFRESH_FORGET_NEW_ROWS);
            }
            facilityFinancialVo.insertRow(newFinancialRow);
        }


        for (Row facilityAmtSummRow : facilityAmtSummRows) {
            String isNew = (String)facilityAmtSummRow.getAttribute("IsNew");


            Row newAmtSummRow = facilityAmtSummVo.createRow();
            Number oldFacilityAmtSeq =
                (Number)facilityAmtSummRow.getAttribute("CompId");
            Number facilityAmtSeq =
                getSequenceVal("XXX_FSA_FIN_FAC_AMT_SUM_SEQ");
            newAmtSummRow.setAttribute("CompId", facilityAmtSeq);
            newAmtSummRow.setAttribute("TxnId", facilityTxnSeq);
            newAmtSummRow.setAttribute("Component1",
                                       facilityAmtSummRow.getAttribute("Component1"));
            newAmtSummRow.setAttribute("UsedAmount",
                                       facilityAmtSummRow.getAttribute("UsedAmount"));
            newAmtSummRow.setAttribute("RecoveredAmount",
                                       facilityAmtSummRow.getAttribute("RecoveredAmount"));
            newAmtSummRow.setAttribute("RemainingAmount",
                                       facilityAmtSummRow.getAttribute("RemainingAmount"));
            newAmtSummRow.setAttribute("IsNew", isNew);

            newAmtSummRow.setAttribute("CreatedBy", _user);
            //newAmtSummRow.setAttribute("LastUpdatedBy", _user);
            newAmtSummRow.setAttribute("CreationDate", new Date());
           // newAmtSummRow.setAttribute("LastUpdatedDate", new Date());

            RowSet rs =
                (RowSet)facilityAmtSummRow.getAttribute("FacilityAmtSumDetVO");
            while (rs.hasNext()) {
                Row facilityAmtSummDetRow = rs.next();
                Number facilityAmtDetSeq =
                    getSequenceVal("XXX_FSA_FIN_FAC_AMT_SUM_DET_SE");
                Row newAmtSummDetRow = facilityAmtSummDetVo.createRow();
                newAmtSummDetRow.setAttribute("CompId", facilityAmtSeq);
                newAmtSummDetRow.setAttribute("Id", facilityAmtDetSeq);
                newAmtSummDetRow.setAttribute("Component1",
                                              facilityAmtSummDetRow.getAttribute("Component1"));
                newAmtSummDetRow.setAttribute("UsedAmount",
                                              facilityAmtSummDetRow.getAttribute("UsedAmount"));
                newAmtSummDetRow.setAttribute("RecoveredAmount",
                                              facilityAmtSummDetRow.getAttribute("RecoveredAmount"));
                newAmtSummDetRow.setAttribute("RemainingAmount",
                                              facilityAmtSummDetRow.getAttribute("RemainingAmount"));
                newAmtSummDetRow.setAttribute("CreatedBy", _user);
                ///newAmtSummDetRow.setAttribute("LastUpdatedBy", _user);
                newAmtSummDetRow.setAttribute("CreationDate", new Date());
                //newAmtSummDetRow.setAttribute("LastUpdatedDate", new Date());
                FacilityAmtSumDetVORowImpl amtSummDetailRowImpl =
                    (FacilityAmtSumDetVORowImpl)facilityAmtSummDetRow;
                if (amtSummDetailRowImpl.getEntity(0).getEntityState() ==
                    Entity.STATUS_MODIFIED ||
                    amtSummDetailRowImpl.getEntity(0).getEntityState() ==
                    Entity.STATUS_NEW) {
                    facilityAmtSummDetRow.refresh(Row.REFRESH_UNDO_CHANGES |
                                                  Row.REFRESH_WITH_DB_FORGET_CHANGES |
                                                  Row.REFRESH_FORGET_NEW_ROWS);
                }
                facilityAmtSummDetVo.insertRow(newAmtSummDetRow);
            }
            FacilityAmtSumVORowImpl amtSummRowImpl =
                (FacilityAmtSumVORowImpl)facilityAmtSummRow;
            if (amtSummRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_MODIFIED ||
                amtSummRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_NEW) {
                facilityAmtSummRow.refresh(Row.REFRESH_UNDO_CHANGES |
                                           Row.REFRESH_WITH_DB_FORGET_CHANGES |
                                           Row.REFRESH_FORGET_NEW_ROWS);
            }
            facilityAmtSummVo.insertRow(newAmtSummRow);
        }


        /**
         *
         * Facility Extension
         */
        for (Row facilityExtnRow : facilityExtnRows) {
            Number facilityExtnSeq =
                getSequenceVal("XXX_FSA_FIN_FACILITY_EXTN_SEQ");
            Row newfacilityExtnRow = facilityExtnVo.createRow();
            newfacilityExtnRow.setAttribute("Id", facilityExtnSeq);
            newfacilityExtnRow.setAttribute("TxnId", facilityTxnSeq);
            newfacilityExtnRow.setAttribute("FacilityDate",
                                            facilityExtnRow.getAttribute("FacilityDate"));
            newfacilityExtnRow.setAttribute("ExpiryDate",
                                            facilityExtnRow.getAttribute("ExpiryDate"));
            newfacilityExtnRow.setAttribute("Amount",
                                            facilityExtnRow.getAttribute("Amount"));
            newfacilityExtnRow.setAttribute("FacilityType",
                                            facilityExtnRow.getAttribute("FacilityType"));
            FacilityExtnVORowImpl extnRowImpl =
                (FacilityExtnVORowImpl)facilityExtnRow;
            if (extnRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_MODIFIED ||
                extnRowImpl.getEntity(0).getEntityState() ==
                Entity.STATUS_NEW) {
                facilityExtnRow.refresh(Row.REFRESH_UNDO_CHANGES |
                                        Row.REFRESH_WITH_DB_FORGET_CHANGES |
                                        Row.REFRESH_FORGET_NEW_ROWS);
            }
            facilityExtnVo.insertRow(newfacilityExtnRow);
        }

        this.getTransaction().commit();
        // facilityTxnVO.setWhereClause("FacilityTxnEO.TXN_ID = 56 ");
        facilityTxnVO.setCurrentRow(newTxnRow);
        facilityHdrVO.setNamedWhereClauseParam("facilityNumber", facNum);
        facilityHdrVO.executeQuery();
        Row[] hdrRowss = facilityHdrVO.getAllRowsInRange();
        facilityTxnVO.executeEmptyRowSet();
        facilityTxnVO.setNamedWhereClauseParam("docNum",
                                               hdrRowss[0].getAttribute("DocumentNumber"));
        facilityTxnVO.executeQuery();
        return "SUCCESS";
    }

    /**
     *
     * Method to get sequence value based on Sequence Name
     */
    public Number getSequenceVal(String sequenceName) {
        Number sequenceValue = new Number();
        if (sequenceName != null && !"".equals(sequenceName)) {
            SequenceImpl seqImpl =
                new SequenceImpl(sequenceName, getDBTransaction());
            sequenceValue = seqImpl.getSequenceNumber();
        }
        return sequenceValue;
    }

    /**
     * Container's getter for FacilityLovVo1.
     * @return FacilityLovVo1
     */
    public ViewObjectImpl getFacilityLovVo1() {
        return (ViewObjectImpl)findViewObject("FacilityLovVo1");
    }

    /**
     * Container's getter for FacilityExtnVO1.
     * @return FacilityExtnVO1
     */
    public ViewObjectImpl getFacilityExtnVO1() {
        return (ViewObjectImpl)findViewObject("FacilityExtnVO1");
    }


    /**
     * Container's getter for FacilityExtnVO2.
     * @return FacilityExtnVO2
     */
    public ViewObjectImpl getFacilityExtnVO2() {
        return (ViewObjectImpl)findViewObject("FacilityExtnVO2");
    }

    /**
     * Container's getter for FacilityTxnExtnVL1.
     * @return FacilityTxnExtnVL1
     */
    public ViewLinkImpl getFacilityTxnExtnVL1() {
        return (ViewLinkImpl)findViewLink("FacilityTxnExtnVL1");
    }

    /**
     * Container's getter for FacilityLegalEntityVO1.
     * @return FacilityLegalEntityVO1
     */
    public ViewObjectImpl getFacilityLegalEntityVO1() {
        return (ViewObjectImpl)findViewObject("FacilityLegalEntityVO1");
    }

    /**
     * Container's getter for FacilityBusinessUnitVO1.
     * @return FacilityBusinessUnitVO1
     */
    public ViewObjectImpl getFacilityBusinessUnitVO1() {
        return (ViewObjectImpl)findViewObject("FacilityBusinessUnitVO1");
    }
}
